server:
  port: ${port:8080}
  servlet:
    context-path: /cursomc

spring: 
  h2: 
    console:
      settings: 
        web-allow-others: true
      enabled: true
      path: /bdcursomc
      
  datasource: 
    url: jdbc:h2:mem:cursomc;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    platform: h2   
    
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # No JDBC URL: jdbc:h2:file:~/test